global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['trade-rabbitmq:15692']

  - job_name: 'trade-api'
    static_configs:
      - targets: ['trade-api:8080']

  - job_name: 'trade-worker'
    static_configs:
      - targets: ['trade-worker:9091']